### ISSUE TITLE
Appcelerator Ti v8 runtime crashing on upcoming Android version (Q beta)

### ISSUE THREAD

**Issue by 15characterlimi** [appcelerator/titanium_mobile#10852]
**Describe the bug**

Hi! I'm writing from the Android team.
Appcelerator Ti does not safely deal with the addition of the mapping from file extension "json" to MIME type "application/json" in Android Q, leading to Android Q-specific problems at runtime observed in at least four different apps. In one app, it looks like there may be an issue in JavaScript code trying to JSON.parse() an already-parsed JSON object (ie. which has already gone through JSON.parse()). The JavaScript source code isn't clear - it might be bundled with Appcelerator Ti, or it might be app code (perhaps going through TiVerify).

**To Reproduce**
Unfortunately you'll have to find an affected app yourself (not sure if I should disclose particular apps here), but it shouldn't be too difficult because most of the ones I checked are affected.

1. Use Android Q Beta from https://developer.android.com/preview
2. Start an app built on top of Appcelerator Ti.
3. Unfortunately the behavior differs from app to app. Some show error dialogs, some show stacktraces such as the below examples.

**Expected behavior**
Apps work normally and do not show any error dialogs / log any errors.

**Environment**
Observed on various versions of Appcelerator Ti, eg. 7.0.2 and 7.5.0

**Logs**:
One app:

TiExceptionHandler: (main) [22,246] [object TiBlob]
TiExceptionHandler:  ^
TiExceptionHandler: SyntaxError: Unexpected token o in JSON at position 1
TiExceptionHandler:     at JSON.parse (<anonymous>)
TiExceptionHandler:     at Object.exports.loadTiLangFile (/lib/shared/lang.js:94:13)
TiExceptionHandler:     at Object.exports.loadLangFile (/lib/shared/lang.js:80:19)
TiExceptionHandler:     at Object.exports.getString (/lib/shared/lang.js:131:41)
TiExceptionHandler:     at Object.exports._ (/lib/shared/lang.js:172:13)
TiExceptionHandler:     at ConnectionEvents (/events/connection.js:9:19)
TiExceptionHandler:     at /app.js:45:29
TiExceptionHandler:     at Module._runScript (ti:/module.js:613:9)
TiExceptionHandler:     at Module.load (ti:/module.js:105:7)
TiExceptionHandler:     at Module.loadJavascriptText (ti:/module.js:457:9)
V8Exception: Exception occurred at undefined:1: Uncaught SyntaxError: Unexpected token o in JSON at position 1

Note that "Unexpected token o" is an error message from json-parser bundled inside V8 which is bundled inside Appcelerator Ti. This particular error suggests that JSON.parse() was called with an object that is already something other than a JSON string, for example and already-parsed JSON object.

Here's a log from a different app:

TiExceptionHandler: (main) [560,560] ----- Titanium Javascript Runtime Error -----
TiExceptionHandler: (main) [0,560] - In undefined:1,2
TiExceptionHandler: (main) [1,561] - Message: Uncaught SyntaxError: Unexpected token o in JSON at position 1
TiExceptionHandler: (main) [0,561] - Source: [object TiBlob]
V8Exception: Exception occurred at undefined:1: Uncaught SyntaxError: Unexpected token o in JSON at position 1

All affected apps have in common that they call android.webkit.MimeTypeMap.getMimeTypeFromExtension("json"), which returns "application/json" on Android Q Beta. On earlier versions of Android, it returned null. Changing MimeTypeMap to the behavior from before Android Q fixes the problematic issues (app errors).

Here's an example call trace of how Appcelerator Ti's TiBlob.blobFromFile is calling MimeTypeMap.getMimeTypeFromExtension("json"); this triggers an unknown different code path later on which leads to the error.

   android.webkit.MimeTypeMap.getMimeTypeFromExtension(MimeTypeMap.java:92)
at org.appcelerator.titanium.util.TiMimeTypeHelper.getMimeTypeFromFileExtension(TiMimeTypeHelper.java:39)
at org.appcelerator.titanium.util.TiMimeTypeHelper.getMimeType(TiMimeTypeHelper.java:73)
at org.appcelerator.titanium.util.TiMimeTypeHelper.getMimeType(TiMimeTypeHelper.java:30)
at org.appcelerator.titanium.TiBlob.blobFromFile(TiBlob.java:107)
at org.appcelerator.titanium.io.TiFile.read(TiFile.java:383)
at org.appcelerator.titanium.TiFileProxy.read(TiFileProxy.java:286)
at org.appcelerator.kroll.runtime.v8.V8Object.nativeCallProperty(Native Method)
at org.appcelerator.kroll.runtime.v8.V8Object.callProperty(V8Object.java:75)
at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1210)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7141)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)

Here is another stacktrace (slightly different from TiFileProxy.read() upwards):

android.webkit.MimeTypeMap.getMimeTypeFromExtension(MimeTypeMap.java:92)
at org.appcelerator.titanium.util.TiMimeTypeHelper.getMimeTypeFromFileExtension(TiMimeTypeHelper.java:33)
at org.appcelerator.titanium.util.TiMimeTypeHelper.getMimeType(TiMimeTypeHelper.java:58)
at org.appcelerator.titanium.util.TiMimeTypeHelper.getMimeType(TiMimeTypeHelper.java:25)
at org.appcelerator.titanium.TiBlob.blobFromFile(TiBlob.java:113)
at org.appcelerator.titanium.io.TiResourceFile.read(TiResourceFile.java:121)
at org.appcelerator.titanium.TiFileProxy.read(TiFileProxy.java:257)
at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:936)
at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1159)
at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:363)
at ti.modules.titanium.ui.widget.listview.ListViewProxy.handleMessage(ListViewProxy.java:322)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:214)
at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:118)

Overall, I'm not sure where the buggy code is that does the wrong thing when a TiBlob's mimetype is "application/json" but that does the right thing when the mimetype is null. It might be somewhere Appcelerator Titanium, for example in module.js from the Appcelerator Ti's runtime library, or it might be in multiple apps. Either way, the fact that TiBlob.blobFromFile() depends on behavior that changes between Android versions is part of the problem:

[...]
   public static TiBlob blobFromFile(TiBaseFile file, String mimeType) {
        if (mimeType == null) {
            mimeType = TiMimeTypeHelper.getMimeType(file.nativePath());
        }

Feel free to respond here if you have any follow-on questions.

**Comment by jquick-axway** [comment]
Thanks for the details. I'm sure this will be helpful on our end. And sorry about the late response. We already have a ticket for the Android Q JSON mimetype issue here: [TIMOB-26954](https://jira.appcelerator.org/browse/TIMOB-26954).

The `JSON.parse()` method throwing an exception is what surprises me though. Hmm...

**Comment by hansemannn** [comment]
This can be closed.

**Comment by jquick-axway** [comment]
This issue was resolved in Titanium 8.1.0.
